<?php

namespace App\Helpers;

use Carbon\Carbon;

class CommonHelper
{
    public static function getUploadPath()
    {
        return public_path('storage');
    }

    public static function getInvoiceFooterText($initial_text)
    {
        $text = "<div style='text-align: center;font-size:10px;line-height:1.3;'>".$initial_text."Powered By: <b>".CommonHelper::getCompanyInformation()['name']."</b> | Hotline: ".CommonHelper::getCompanyInformation()['hotline']." <br> Generated By - www.retinasoft.com.bd</div>";
        return $text;
    }
    public static function uploadFile($file, $name, $folder_name)
    {
        $url = $file->storeAs($folder_name, $name);
        return "storage/" . $url;
    }

    public static function getBloodGroups()
    {
        return config('sitedata.blood_groups');
    }

    public static function getPaymentType()
    {
        return config('sitedata.payment_type');
    }

    public static function dateRangeItem(){
        return config('sitedata.day_range_list');
    }

    public static function getCompanyInformation(){
        return config('sitedata.company_information');
    }

    public static function getRealStringSubStr($string, $limit, $extra = '...')
    {
        $string = strip_tags($string);
        if (strlen($string) > $limit) {
            $string = substr($string, 0, $limit).$extra;
        }
        return $string;
    }


    public static function removeUnderscore($string, $uppercase = false)
    {
        $string = str_replace('_', ' ', $string);
        if ($uppercase === true) {
            $string = ucwords($string);
        }
        return $string;
    }

    public static function showDate($date)
    {
        if ($date != '') {
            $date = Carbon::make($date)->format('F j, Y');
        }
        return $date;
    }

    public static function getDayDate($date)
    {
        if ($date != '') {
            $date = Carbon::make($date)->format('d');
        }
        return $date;
    }

    public static function getShortMonth($date)
    {
        if ($date != '') {
            $date = Carbon::make($date)->format('M');
        }
        return $date;
    }

    public static function showDateTime($date)
    {
        if ($date != '') {
            $date = Carbon::make($date)->format('F j, Y, g:i a');
        }
        return $date;
    }

    public static function showViewMore($string, $limit)
    {
        $string = strip_tags($string);
        if (strlen($string) > $limit) {
            return true;
        }
        return false;
    }

    public static function getCurrency()
    {
        return config('sitedata.currency');
    }
}
